version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - app-network
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network
networks:
  app-network:
    driver: bridge